"""
This file demonstrate the use of the tmcmc() routine, which is defined as follows:
tmcmc(fitfun,dim=2,maxstages=20,popsize=1024,lowerbound=[-6,-6],upperbound=[6,6],id=0):

- fitfun: python script name (without the .py extension) that implements the log-likelihood function.
The prototype is: fitfun(x, n), where x is a vector of parameter values and n the number of parameters.
- dim: number of parameters
- maxstages: maximum number of stages that can be performed by the TMCMC algorithm
- popsize: number of samples per stage
- lowerbound: lower bound for each parameter
- upperbound: uppoer bound for each parameter
- id: integer identifier for the specific tmcmc() call. The value is appended to the output files generated by the algorithm.
"""


# Import whatever is necessary
import sys
sys.path.append("../lib_python")
from tmcmc import *
from plot_gen import *

print("calling tmcmc")

#logEv=tmcmc('fitfun2', dim=2, maxstages=20, popsize=4096, lowerbound=[-10,-10], upperbound=[10,10], id=2)
logEv=tmcmc('fitfun3', dim=2, maxstages=20, popsize=4096, lowerbound=[-10,0], upperbound=[10,1], id=3)
print("logEv=",logEv[0])

print("tmcmc completed!")

# Output files can be plotted with the following python script:
# python2.7 ../lib/display_gen.py curgen_db_xxx_yyy.txt 2 1 2 
# xxx = id of the tmcmcm run, yyy = stage number, 2 1 2 : number of parameters, first parameter (x-axis), second parameter (y-axis) 

#plot_gen('curgen_db_002_003.txt', dim=2, i=1, j=2, show=1, save=0)

plot_gen('curgen_db_003_009.txt',dim=2,i=1,j=2,show=1,save=0)
